server.port=8083
spring.application.name=order-service
spring.datasource.url=jdbc:h2:mem:orderdb_prod
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.h2.console.enabled=false
spring.h2.console.path=/h2-console
logging.level.com.microservices=ERROR
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
app.environment=prod
app.message=order-service running in PROD mode
app.feature.enabled=true
app.debug-mode=false
