# ============================================================
# USER SERVICE — QA PROFILE
# ============================================================
server.port=8081
spring.application.name=user-service

spring.datasource.url=jdbc:h2:mem:userdb_qa
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.com.microservices=INFO
logging.level.org.springframework.web=INFO

management.endpoints.web.exposure.include=health,info,metrics,refresh
management.endpoint.health.show-details=always

app.environment=qa
app.message=User Service running in QA/TESTING mode
app.feature.registration-enabled=true
app.max-users=200
app.debug-mode=false
