# ============================================================
# USER SERVICE — PROD PROFILE
# ============================================================
server.port=8081
spring.application.name=user-service

# In PROD use real DB — replace with actual values
spring.datasource.url=jdbc:h2:mem:userdb_prod
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

spring.h2.console.enabled=false

logging.level.com.microservices=ERROR
logging.level.root=WARN

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

app.environment=prod
app.message=User Service running in PRODUCTION mode
app.feature.registration-enabled=true
app.max-users=10000
app.debug-mode=false
